spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springboot-mongo

telegram:
  bot:
    username: ${}
    token: ${}

logging:
  level:
    root: info
    org:
      apache:
        http: debug
    #org.springframework.jdbc.core: TRACE
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(%-4.4line){blue} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: "./logs"
  logback:
    rollingpolicy:
      max-file-size: 10MB